"""Modules Forge. Importer ce package enregistre les modules livrés."""
from . import demo     # noqa: F401  (demo.fingerprint — no-op)
from . import recon    # noqa: F401  (recon.httpx, recon.nmap)
from . import recon_surface  # noqa: F401  (recon.subdomains/dns/js_endpoints/urls/tech — surface passive)
from . import recon_active   # noqa: F401  (recon.content/secrets/waf — reachability active gouvernée)
from . import web      # noqa: F401  (web.nuclei)
from . import access_control  # noqa: F401  (access_control.idor — IDOR/BOLA 2-comptes, CWE-639 ; access_control.privesc — PrivEsc vertical, CWE-269)
from . import ssrf     # noqa: F401  (ssrf.callback — SSRF callback-vérifié, CWE-918 ; ssrf.xspa — XSPA port-scan différentiel)
from . import auth     # noqa: F401  (auth.takeover — ATO/auth-bypass à preuve, CWE-287/640)
from . import cors     # noqa: F401  (cors.credentials — CORS-credentials à preuve, CWE-942)
from . import injection  # noqa: F401  (ssti.eval, path.traversal, sqli.probe — injections à preuve bénigne)
from . import xxe      # noqa: F401  (xxe.probe — XXE à preuve bénigne OOB/canari, CWE-611)
from . import rfi      # noqa: F401  (rfi.probe — RFI marqueur bénin inclus, CWE-98)
from . import clientflow  # noqa: F401  (xss.reflected, redirect.open, csrf.state_change ; xss.stored via browser — flux client à preuve)
from . import tokenapi  # noqa: F401  (jwt.weakness, graphql.access — oracles token/API à preuve compte-opérateur)
from . import rce      # noqa: F401  (rce.probe — RCE gouvernée pentest-only, plancher exploit, CWE-78)
from . import business_logic  # noqa: F401  (business_logic.scan — scaffold semi-automatisé pentest-only, CWE-840)
from . import origin   # noqa: F401  (origin.find — IP d'origine derrière CDN)
from . import evasion  # noqa: F401  (evasion.xhr, evasion.turnstile, evasion.idor_intercept, evasion.discover)
from . import msf       # noqa: F401  (msf.module — connecteur msfrpcd, opérateur opt-in)
from . import burp      # noqa: F401  (burp.scan — connecteur REST API Burp Suite)
from .registry import REGISTRY, register, get, kinds, Module  # noqa: F401
